services:
  nginx:
    image: nginx_prod
    build:
      context: ./
      dockerfile: ./backend/nginx/dockerfile.prod
    ports: !override
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    env_file:
      - ./backend/.env # create before deployment
