services:
  nginx:
    image: nginx_prod
    build:
      context: ./
      dockerfile: ./backend/nginx/dockerfile.prod
    volumes:
      - ./backend/nginx/prod.nginx.conf:/etc/nginx/nginx.conf
    ports: !override
      - 8080:80
      - 8443:443
