services:
  backend:
    image: backend_dev
    container_name: backend_dev
    build:
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./shared/src:/shared/src
      - ./backend/src:/backend/src
      - ./backend/sql:/backend/sql
    environment:
      NODE_ENV: development

  frontend:
    image: frontend_dev
    container_name: frontend_dev
    build:
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./shared/src:/shared/src
      - ./docs:/docs
      - ./frontend/src:/frontend/src

  nginx:
    volumes:
      - ./backend/nginx/dev.nginx.conf:/etc/nginx/nginx.conf
