FROM node:25-alpine

# INSTALL
WORKDIR /shared
COPY /shared/package*.json /shared/
RUN npm install

WORKDIR /backend
COPY /backend/package*.json /backend/
RUN npm install

# BUILD
COPY /shared /shared/
COPY /backend /backend/
RUN mkdir -p /data/avatars
COPY /backend/src/defaultAvatar.jpg /data/avatars/default.jpg

# HOST
CMD ["npm", "run", "buildDevAndServerDev"]
