FROM nginx:1.29.6-alpine

RUN apk add --no-cache openssl && \
	mkdir -p /etc/nginx/ssl && \
	openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
		-keyout /etc/nginx/ssl/private.key \
		-out /etc/nginx/ssl/public_certificate.crt \
		-subj "/CN=localhost"

EXPOSE 80 443
