FROM nginx:1.29.6-alpine

RUN apk add --no-cache openssl && \
	mkdir -p /etc/nginx/ssl && \
	openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
		-keyout /etc/nginx/ssl/private.key \
		-out /etc/nginx/ssl/public_certificate.crt \
		-subj "/CN=localhost"

COPY ./backend/nginx/nginx.conf.template /etc/nginx/nginx.conf.template

CMD ["/bin/sh", "-c", "envsubst '${HTTP_PORT} ${HTTPS_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
